### ISSUE TITLE
set up HPC env

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/SMOTE#1]

**Comment by WeiFoo** [comment]
done

**Comment by timm** [comment]
cool... zhe was reporting a 25-fold time speed up. what do you get?

**Comment by WeiFoo** [comment]
with naive bayes.

I run one data set( **drupal**) at my local machine and also submit to HPC,

local machine finished 3/12 expriments(100,500,900 features) in 47 minutes. the 
HPC finished 12/12 in 30 minutes.

I can't run this expriment on local machine any more since it's heating. HPC is definitely faster.

**Comment by timm** [comment]
> local machine finished 3/12 expriments(100,500,900 features) in 47 mins

so 12/12 would take 4*47 = 188 mins

> HPC finished 12/12 in 30 minutes.

speed up = 188/30 = 6 fold.

huh. probably much an be tweaked here.

t
