### ISSUE TITLE
using "hash"method to extract features would generate negative values

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/SMOTE#6]
Something wrong here.

**Comment by azhe825** [comment]
Use this:

```
hasher = FeatureHasher(n_features=n_features, non_negative=non_negative)
```

this change will not affect classification result

**Comment by timm** [comment]
checking in here. is this running on "SE" data or "legal" data (i.e. specific data sets within stackexchange)

**Comment by WeiFoo** [comment]
this is SE data. and I need to check some details. right now, tfidf method works. so I use it to work on tuning stuff. I will go to check "hash" later on when all tuning methods running.
This bug is not on my priority list now.

**Comment by timm** [comment]
@azhe825  is reporting that abs(hash) is not doing mich different to hash, anyway.

https://github.com/ai-se/e-disc/issues/54

so maybe we can close this thread?
